Projekt MVP/ProjektMVP/ProjektMVP/Controllers/ZarzadzajUzytkownikamiController.cs
using System.Security.Policy;

namespace ProjektMVP.Controllers
{
    using Models;
    using Models.Interfaces;
    using System.Web.Mvc;
    using DTO;
    using Interfaces;
    using System.Collections.Generic;
    using Microsoft.Ajax.Utilities;

    [RoutePrefix("users")]
    public class ZarzadzajUzytkownikamiController : Controller, IZarzadzajUzytkownikamiPresenter
    {
        private static IUzytkownikModel uzytkownikModel;

        public ZarzadzajUzytkownikamiController()
        {
            uzytkownikModel = new UzytkownikModel();
        }

        #region Maciej Skałba
        //Iteracja 1
        public ActionResult WyswietlFormularzEdycjiKontaAktualnegoUzytkownika(int uzytkownikId)
        {
            var uzytkownik = uzytkownikModel.PobierzUzytkownika(uzytkownikId);
            var dto = UzytkownikMapper.MapEntityToDto(uzytkownik);
            return View("FormularzEdycjiKontaUzytkownika", dto);
        }

        public ActionResult EdytujInformacjeOKoncieButton(UzytkownikDTO uzytkownik)
        {
            var result = EdytujInformacjeOKoncie(uzytkownik);
            if(result == true)
                return View("Index");
            else
                return View("Error");
        }

        public bool EdytujInformacjeOKoncie(UzytkownikDTO uzytkownik)
        {
            var entity = UzytkownikMapper.MapDtoToEntity(uzytkownik);
            var result = uzytkownikModel.EdytujInformacjeOKoncie(entity);
            return result;
        }

        public ActionResult WyswietlFormularzDodaniaKartyKredytowej(int uzytkownikId)
        {
            return View("FormularzDodaniaKartyKredytowej", uzytkownikId);
        }

        public ActionResult ZapiszKarteKredytowaButton(int uzytkownikId, KartaKredytowaDTO karta)
        {
            var result = ZapiszKarteKredytowa(uzytkownikId, karta);
            if (result == true)
                return View("FormularzInformacjiOKarcieKredytowej");
            else
                return View("Error");
        }

        public bool ZapiszKarteKredytowa(int uzytkownikId, KartaKredytowaDTO karta)
        {
            var entity = KartaKredytowaMapper.MapDtoToEntity(karta);
            var result = uzytkownikModel.ZapiszKarteKredytowa(uzytkownikId, entity);
            return result;
        }
        #endregion

        #region Robert Witkowski
        //Iteracja 1
        [Route("formularz")]
        [HttpGet]
        public ActionResult WyswietlFormularzDodawaniaLubEdytowaniaUzytkownika(UzytkownikDTO dto)
        {
            return View("FormularzDodawaniaLubEdytowaniaUzytkownika");
        }

        [Route("formularz")]
        [HttpPost]
        public ActionResult DodajLubEdytujUzytkownik(UzytkownikDTO dto)
        {
            if (dto.Id.HasValue)
            {
                var newDto = EdytujUzytkownika(dto);
                ViewBag.Message = "Użytkownik został edytowany."; 
                return View("FormularzDodawaniaLubEdytowaniaUzytkownika", newDto);
            }
            else
            {
                dto.Id = DodajUzytkownika(dto);
                ViewBag.Message = "Nowy użytkownik został dodany.";
                ModelState.Clear();
                return View("FormularzDodawaniaLubEdytowaniaUzytkownika", dto);
            }
        }

        public int DodajUzytkownika(UzytkownikDTO dto)
        {
            return uzytkownikModel.ZapiszNowegoUzytkownika(UzytkownikMapper.MapDtoToEntity(dto));
        }

        public UzytkownikDTO EdytujUzytkownika(UzytkownikDTO dto)
        {
            var edytowanyUzytkownik = uzytkownikModel.EdytujNowegoUzytkownika(UzytkownikMapper.MapDtoToEntity(dto));
            return UzytkownikMapper.MapEntityToDto(edytowanyUzytkownik);
        }

        //Iteracja 2
        [Route("mojekonto/{uzytkownikId:int}")]
        [HttpGet]
        public ActionResult WyswietlInformacjeOKoncie(int uzytkownikId)
        {
            var uzytkownik = PobierzUzytkownika(uzytkownikId);
            return View("InformacjeOKoncie", uzytkownik);
        }

        [Route("zawies/{uzytkownikId}")]
        [HttpGet]
        public ActionResult ZawiesUzytkownikaButton(int uzytkownikId)
        {

            var uzytkownik = PobierzUzytkownika(uzytkownikId);
            return View("InformacjeOKoncie", uzytkownik);
        }

        public UzytkownikDTO PobierzUzytkownika(int uzytkownikId)
        {
            var uzytkownik = uzytkownikModel.PobierzUzytkownika(uzytkownikId);
            return UzytkownikMapper.MapEntityToDto(uzytkownik);
        }

        public bool ZawiesUzytkownika(int uzytkownikId)
        {
            return uzytkownikModel.ZawiesUzytkownika(uzytkownikId);
        }

        //Iteracja 3
        [Route("usunieciekonta/{uzytkownikId}/{opis}")]
        [HttpGet]
        [HttpPost]
        public ActionResult WyswietlFormularzProsbyOUsuniecieKonta(int uzytkownikId, string opis)
        {
            if (opis.IsNullOrWhiteSpace())
                return View("FormularzProsbyOUsuniecieKonta", uzytkownikId);
            else
            {
                WyslijProsbeOUsuniecieKonta(uzytkownikId, opis);
                return View("Index");
            }
        }

        public bool WyslijProsbeOUsuniecieKonta(int uzytkownikId, string opis)
        {
            return uzytkownikModel.WyslijProsbeOUsuniecieKonta(uzytkownikId, opis);
        }
        #endregion

        public UzytkownikDTO EdytujKarteKredytowa(UzytkownikDTO u)
        {
            var edytowanyUzytkownik = uzytkownikModel.EdytujKarteKredytowa(UzytkownikMapper.MapDtoToEntity(u));
            return UzytkownikMapper.MapEntityToDto(edytowanyUzytkownik);
        }

        public List<UzytkownikDTO> WezListeUzytkownikow()
        {
            List<UzytkownikDTO> tmp = new List<UzytkownikDTO>();

            foreach (var uzytkownik in uzytkownikModel.PobierzListeUzytkownikow())
                tmp.Add(UzytkownikMapper.MapEntityToDto(uzytkownik));

            return tmp;
        }
    }
}

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/FormularzDodaniaKartyKredytowej.cshtml
@{
    ViewBag.Title = "FormularzDodaniaKartyKredytowej";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FormularzDodaniaKartyKredytowej</h2>

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/FormularzDodawaniaLubEdytowaniaUzytkownika.cshtml
@model ProjektMVP.DTO.UzytkownikDTO

@{
    ViewBag.Title = "Dodaj/edytuj użytkownika";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj/edytuj użytkownika</h2>

@if (ViewBag.Message != null)
{
    <div style="color:red">@ViewBag.Message</div>
}

@using (Html.BeginForm("DodajLubEdytujUzytkownikActionResult", "ZarzadzajUzytkownikami", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Id)
                @Html.EditorFor(model => model.Imie, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Imie, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HotelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HotelId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PermissionsId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PermissionsId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PermissionsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Karta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Karta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Karta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @if (Model?.Id != null)
                {
                    <input type="submit" value="Edytuj" class="btn btn-default" />
                }
                else
                {
                    <input type="submit" value="Dodaj" class="btn btn-default" />
                }
            </div>
        </div>
    </div>
}

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/FormularzEdycjiKontaUzytkownika.cshtml
@model ProjektMVP.DTO.UzytkownikDTO

@{
    ViewBag.Title = "FormularzEdycjiKontaUzytkownika";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FormularzEdycjiKontaUzytkownika</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UzytkownikDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Karta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Karta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Karta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/FormularzInformacjiOKarcieKredytowej.cshtml
@{
    ViewBag.Title = "FormularzInformacjiOKarcieKredytowej";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FormularzInformacjiOKarcieKredytowej</h2>

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/FormularzProsbyOUsuniecieKonta.cshtml
@{
    ViewBag.Title = "FormularzProsbyOUsuniecieKonta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FormularzProsbyOUsuniecieKonta</h2>

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

Projekt MVP/ProjektMVP/ProjektMVP/Views/ZarzadzajUzytkownikami/InformacjeOKoncie.cshtml
@model ProjektMVP.DTO.UzytkownikDTO

@{
    ViewBag.Title = "Informacje o koncie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Informacje o koncie</h2>

<div>
    <h4>Uzytkownik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PermissionsId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PermissionsId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Karta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Karta)
        </dd>

    </dl>
</div>