Projekt MVP/ProjektMVP/ProjektMVP/Controllers/DaneRezerwacjiController.cs
using ProjektMVP.Controllers.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using ProjektMVP.Models;
using ProjektMVP.Models.Interfaces;
using ProjektMVP.DTO;

namespace ProjektMVP.Controllers
{
#pragma warning disable CS0162 // Unreachable code detected

    [RoutePrefix("Rezerwacja")]
    public class DaneRezerwacjiController : Controller, IDaneRezerwacjiPresenter
    {
        private static IPlatnosciModel _platnosc;
        private static IRezerwacjaModel _rezerwacja;

        public DaneRezerwacjiController()
        {
            _platnosc = new PlatnosciModel();
            _rezerwacja = new RezerwacjaModel();
        }

        #region Iteracja1

        public bool ZaksiegujPlatnosc(PlatnoscEntity platnosc)
        {
            throw new NotImplementedException();

            _platnosc.DodajPlatnosc(platnosc);
            return true;
        }

        public string ZapiszDoPliku(PlatnoscEntity platnosc, PlatnoscFormatZapisu format)
        {
            throw new NotImplementedException();

            // Utworz dokument ze wzgledu na format
            if (format == PlatnoscFormatZapisu.FormatTXT) {
                var document = FormatTxt(platnosc);
            } else {
                // inne formaty
            }

            // String bedzie zastapiony typem File w przyszlosci
            return "File()";
        }

        public string FormatTxt(PlatnoscEntity platnosc)
        {
            throw new NotImplementedException();
        }

        public void Drukuj(PlatnoscEntity platnosc)
        {
            //drukowanie...
        }
        #endregion

        #region Iteracja2

        [Route("Extend/{dto.Id}")]
        [HttpGet]
        public ActionResult WyswietlPrzedluzPobyt(RezerwacjaPrzedluzPobytDTO dto)
        {
            return View("FormularzPrzedluzPobyt");
        }

        [Route("Extend/{dto.Id}")]
        [HttpPost]
        public ActionResult PrzedluzPobyt(RezerwacjaPrzedluzPobytDTO dto)
        {
            var result = _rezerwacja.PrzedluzPobyt(dto);
            ViewBag.Success = (Nullable<bool>)result;

            return View("WyswietlKomunikatPrzedluzPobyt");
        }

        #endregion
    }
#pragma warning restore CS0162 // Unreachable code detected
}

Projekt MVP/ProjektMVP/ProjektMVP/Views/DaneRezerwacji/FormularzPrzedluzPobyt.cshtml
@model ProjektMVP.DTO.RezerwacjaPrzedluzPobytDTO

@{
    ViewBag.Title = "Przedluz Pobyt";
}

<h2>Formularz przedłużenia rezerwacji</h2>

@* Error Message *@
@if (ViewBag.Message != null) {
    <div style="color:red">@ViewBag.Message</div>
}


@using (Html.BeginForm("PrzedluzPobyt", "DaneRezerwacji", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Przedłuż" class="btn btn-default" />
                <input type="button" value="Cofnij" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Home")'" />
            </div>
        </div>

    </div>
}

Projekt MVP/ProjektMVP/ProjektMVP/Views/DaneRezerwacji/WyswietlKomunikatPrzedluzPobyt.cshtml
@{
    ViewBag.Title = "WyswietlKomunikatPrzedluzPobyt";
}

@{if (ViewBag.Success != null && ViewBag.Success) {
        <h2>Przedłużono datę pobytu.</h2>
        <p>Termin rezerwacji został przedłużony do wybranej przez Ciebie daty. Prosimy o uiszczenie opłaty za dodatkowe dni pobytu. 
        <br/>Dziękujemy.</p>
    } else {
        <h2>Brak miejsc.</h2>
        <p>Przepraszamy, ale nie ma możliwości przedłużenia pobytu. Prosimy o wykwaterowanie się przed zakończeniem doby hotelowej w ostatnim dniu rezerwacji. 
        <br/>Dziękujemy.</p>
    }
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Wróć" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Home")'" />
        </div>
    </div>
}